# Change these first
owner: byzocker-de # Your GitHub organization or username, where this repository lives
repo: status.byzocker.de # The name of this repository

sites:
  - name: byzocker.de
    url:  https://byzocker.de
  - name: Nextcloud
    url:  $URL_NEXTCLOUD
  - name: shlink
    url:  https://l.byzocker.de
  - name: PicoShare
    url:  https://cdn.byzocker.de
  - name: Jellyfin
    url: $URL_JELLYFIN
  - name: Tandoor
    url: $URL_TANDOOR
  - name: Vaultwarden
    url: $URL_VW
    
assignees:
  - byzocker
  
status-website:
  theme: dark
  cname: status.byzocker.de
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: byzocker.de
  introTitle: "status.byzocker.de"
  introMessage: This status page displays the uptime and current status for my public facing services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
